# Generated by Django 4.2.23 on 2025-06-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_services', '0002_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Service category image', null=True, upload_to='services/'),
        ),
    ]
