# Generated by Django 4.2.23 on 2025-06-26 12:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_services', '0006_quoterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-booked_at'], 'verbose_name': 'Service Booking', 'verbose_name_plural': 'Service Bookings'},
        ),
        migrations.RenameField(
            model_name='servicebooking',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address_line_1',
            field=models.CharField(default='Jaipur', max_length=255),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='city',
            field=models.CharField(default='Jaipur', max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='contact_email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='contact_phone',
            field=models.CharField(default='9829000000', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='final_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('check', 'Check')], default='card', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial Payment'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='postal_code',
            field=models.CharField(default='302001', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 26, 12, 43, 27, 437745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='preferred_time_slot',
            field=models.CharField(choices=[('morning', 'Morning (8 AM - 12 PM)'), ('afternoon', 'Afternoon (12 PM - 4 PM)'), ('evening', 'Evening (4 PM - 8 PM)'), ('flexible', 'Flexible')], default='flexible', max_length=50),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('normal', 'Normal Priority'), ('high', 'High Priority'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('other', 'Other')], default='residential', max_length=50),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_description',
            field=models.TextField(default='test', help_text='Detailed description of the service needed'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Any special requirements or notes', null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='state_province',
            field=models.CharField(default='Rajasthan', max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
