# Generated by Django 4.2.23 on 2025-06-30 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_services', '0007_alter_servicebooking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 9, 26, 11, 433731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
