# Generated by Django 4.2.23 on 2025-06-30 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_services', '0008_alter_servicebooking_preferred_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='gst_rate',
            field=models.IntegerField(choices=[(5, '5% - EV chargers, solar/wind energy devices'), (12, '12% - Mobile phones, solar water heaters'), (18, '18% - Fans, microwaves, laptops, cables'), (28, '28% - ACs, large TVs (>32"), premium audio')], default=18, help_text='GST rate for this category'),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 30, 11, 11, 24, 847664, tzinfo=datetime.timezone.utc)),
        ),
    ]
