# Generated by Django 4.2.23 on 2025-06-30 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electric_services', '0009_productcategory_gst_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default='', max_length=20, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping_address', models.TextField(default='')),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='servicebooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='alternate_phone',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='assigned_technician',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='completed_date',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='country',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='preferred_time_slot',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='state_province',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='preferred_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='preferred_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('product', 'Product Purchase'), ('service', 'Service Booking')], max_length=10)),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gst_rate', models.IntegerField(default=18)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='electric_services.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electric_services.electricproduct')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electric_services.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='electric_services.payment'),
        ),
    ]
