# Generated by Django 4.2.23 on 2025-06-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_services', '0010_order_alter_servicebooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online_payment', 'Online Payment'), ('check', 'Check')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='preferred_time_slot',
            field=models.CharField(blank=True, choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 4:00 PM)'), ('evening', 'Evening (4:00 PM - 8:00 PM)'), ('flexible', 'Flexible')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
